# 默认总配置文件
# 激活 dev 配置
spring:
  profiles:
    active: dev
---
# 指定该环境下的端口
server:
  port: 80
# 指定环境为：生产环境
spring:
  config:
    activate:
      on-profile: prod
---
# 指定该环境下的端口
server:
  port: 8081
# 指定环境为：开发环境
spring:
  config:
    activate:
      on-profile: dev
  #配置应用程序名称
  application:
    name: DreamTreeSharer
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_tree_sharer?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    #配置数据库连接池
    #springboot 内嵌的连接池，速度快
    hikari:
      pool-name: DreamTreeSharerDataPool
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000ms(10分钟)
      maximum-pool-size: 180000
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      #连接超时时，默认是30000(30秒)
      connection-timeout: 30000
      #测试连接是否可用的查询语句
  # 配置热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
# 网易邮箱
  mail:
    host: smtp.163.com
    username: lv_summer_666@163.com
    password: DTHFHCQMVTAFVDVF
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      mail:
        smtp:
          ssl:
            enable: true


#日志级别配置
logging:
  level:
    # spring框架中的日志级别
    org.springframwork.web: info
    # 配置自己项目包下的日志级别
    com.ITIS: info
  #指定 D盘 生成日志文件 spring.log 为默认输出文件
  file:
    path: D:/DreamTreeSharer
    # 指定日志输出格式
  #  pattern:
  #    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} %msg%n
  #    file: %d{yyyy-MM-dd HH:mm:ss} [%thread] --- %-5level %logger{50} --- %msg%n

#  #清除模板引擎缓存 - 然后 ctrl+f9 重新编译页面
#  thymeleaf:
#    cache: false

  #日期格式配置
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis-plus 配置
mybatis-plus:
  # 配置 mapper 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回各实体存放路径
  type-aliases-package: com.ITIS.DreamTreeSharer.entity
  configuration:
    # 开启自动驼峰命名
    map-underscore-to-camel-case: true
#jwt配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  #JWT 加解密使用的密钥
  secret: ITIS.com
  #JWT的超期限时间 - 毫秒
  expiration: 3600
  #JWT 负载中拿到开头
  tokenHead: ITIS